# Site settings
title: Dylan Losey
email:
author: Dylan Losey
description: "Dylan Losey"
baseurl: ""
url: ""
date_format: "%b %-d, %Y"
header_pages:
 - collab.html
 - publications.html
 - talks.html

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
