# Site settings
title: Dylan Losey
email: dlosey@stanford.edu
author: Dylan Losey
description: "Dylan Losey"
baseurl: ""
url: ""
date_format: "%b %-d, %Y"
header_pages:
 - collab.html
 - publications.html
 - talks.html
 - CV.html
 - contact.html

show_social_icons: false
github_username: dylan-losey
twitter_username:
linkedin_username:

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
