# Site settings
title: Dylan Losey
email: losey@vt.edu
author: Dylan Losey
description: "Dylan Losey"
baseurl: ""
url: "http://dylanlosey.com/"
date_format: "%b %-d, %Y"
header_pages:
 - collab.html
 - publications.html
 - talks.html
 - CV.html
 - contact.html

show_social_icons: true
github_username:
twitter_username: loseydp
linkedin_username:
youtube_id: UC2zeiOrB_tt55DRQ4ejz0eg

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
